# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-29 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Raza', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='perro',
            name='Raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.Raza'),
        ),
    ]
