# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-29 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_auto_20170929_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='raza',
            name='Cruze',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raza',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
