# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-29 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0004_auto_20170929_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Sexo',
            field=models.CharField(choices=[('V', 'Varon'), ('M', 'Mujer')], default='V', max_length=2),
        ),
    ]
