# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-29 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0006_auto_20170929_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='micropchip',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
