# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0008_auto_20170929_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Dni',
            field=models.CharField(max_length=9),
        ),
    ]
