# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0011_auto_20171002_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='foto',
        ),
    ]
