# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0012_remove_perro_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dog.Usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='perro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microchip', to='dog.Perro'),
        ),
    ]
