# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0013_auto_20171002_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedade',
            name='perro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.Perro'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.Usuario'),
        ),
    ]
