# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0017_auto_20171004_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='cruze',
            new_name='cruce',
        ),
        migrations.AlterField(
            model_name='perro',
            name='altura',
            field=models.CharField(choices=[('e', 'enano'), ('m', 'mediano'), ('g', 'grande')], default='m', max_length=3),
        ),
    ]
