# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0021_auto_20171023_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dog.Usuario'),
            preserve_default=False,
        ),
    ]
