# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0022_perro_propietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='perro',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propiedade',
            name='perro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.Perro', unique=True),
        ),
        migrations.AddField(
            model_name='propiedade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.Usuario'),
        ),
    ]
