# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0023_auto_20171026_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedade',
            name='perro',
        ),
        migrations.RemoveField(
            model_name='propiedade',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Propiedade',
        ),
    ]
