# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0027_perro_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='foto',
        ),
    ]
