# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-04 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0030_auto_20171201_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(upload_to='dog/static/pic'),
        ),
    ]
