# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-04 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0031_auto_20171204_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='resumen',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
