# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-04 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0033_auto_20171204_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(max_length=5000),
        ),
    ]
