# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0034_auto_20171204_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='resumen',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(upload_to='/dog/images'),
        ),
    ]
