# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0037_auto_20171205_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(upload_to='path_and_rename'),
        ),
    ]
