# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import dog.models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0038_auto_20171208_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(upload_to=dog.models.path_and_rename),
        ),
    ]
