# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-09 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import dog.models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0038_auto_20171208_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='raza',
            name='descripcion',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='raza',
            name='imagen',
            field=models.ImageField(null=True, upload_to=dog.models.path_and_renames),
        ),
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(null=True, upload_to=dog.models.path_and_renamese),
        ),
    ]
