# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import dog.models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0039_auto_20171208_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='raza',
            name='descripcion',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raza',
            name='imagen',
            field=models.ImageField(default=2, upload_to=dog.models.path_and_rename),
            preserve_default=False,
        ),
    ]
