# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0040_auto_20171208_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raza',
            name='imagen',
        ),
    ]
